import = ["/Users/seanpeters/.config/alacritty/rose-pine/rose-pine.toml"]

[shell]
program = "/opt/homebrew/bin/fish"

[env]
TERM = "xterm-256color"

[font]
size = 13.5
offset.y = 5

[font.normal]
family = "FiraCode Nerd Font Mono"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[window]
decorations = "buttonless"

[window.padding]
x = 10
y = 10
