# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$nodejs\
$golang\
$lua\
$php\
$python\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = ' '

[hostname]
ssh_symbol = ''

[directory]
read_only = " "
style = 'cyan'
before_repo_root_style = 'cyan'
repo_root_style = 'bold cyan'
truncation_length = 0
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bright-black"
symbol = ''

[git_status]
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted )](bold red)[($ahead_behind )]($style)[($stashed)](bold red)]($style)"
format = '([$all_status](bold red)[$ahead_behind]($style))'
style = "green"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "bright-black"

[nodejs]
format = '[$symbol($version) ]($style)'
symbol = " "
version_format = "${raw}"

[golang]
format = '[$symbol($version) ]($style)'
symbol = " "
version_format = "${raw}"

[lua]
format = '[$symbol($version) ]($style)'
symbol = " "
version_format = "${raw}"

[php]
format = '[$symbol($version) ]($style)'
symbol = " "
version_format = "${raw}"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "
version_format = "${raw}"
